services:
  - type: web
    name: portfolio-graphql-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: portfolio-graphql-server
          property: port
      - key: MONGODB_URI
        sync: false # This will need to be set manually in Render dashboard
    healthCheckPath: /graphql

  - type: web
    name: portfolio-ui
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_GRAPHQL_ENDPOINT
        fromService:
          type: web
          name: portfolio-graphql-server
          property: host

databases:
  - name: portfolio-mongodb
    databaseName: portfolio
    user: portfoliouser
    plan: free
